name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - flask
  - dlib
  - pip:
     - scikit-learn==0.20.3
     - opencv-python==4.2.0.34
     - scipy==1.4.1
     - six==1.14.0
     - sklearn==0.0
     - urllib3==1.25.9
     - Werkzeug==0.16.1
     - WTForms==2.3.1
     - zipp==3.1.0
     - cmake==3.17.2
     - connexion==2.7.0
     - Flask-Caching==1.8.0
     - Flask-Uploads==0.2.1
     - Flask-WTF==0.14.3
     - numpy==1.18.3